import type { Category, Product } from "@/lib/types";

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-freshwater",
    name: "Freshwater",
    slug: "freshwater",
    description: "River and pond favourites",
    sort_order: 1,
  },
  {
    id: "cat-seawater",
    name: "Seawater",
    slug: "seawater",
    description: "Coastal catch of the day",
    sort_order: 2,
  },
  {
    id: "cat-shellfish",
    name: "Prawns & Shellfish",
    slug: "shellfish",
    description: "Prawns, crabs, and more",
    sort_order: 3,
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod-rohu",
    category_id: "cat-freshwater",
    name: "Rohu",
    slug: "rohu",
    description: "Firm freshwater favourite — ideal for curry and fry.",
    cut_notes: "Cleaned, steak-cut on request",
    unit: "kg",
    price_paise: 28000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.5,
    categories: DEMO_CATEGORIES[0],
    inventory: {
      product_id: "prod-rohu",
      qty_on_hand: 45,
      reserved_qty: 2,
      low_stock_threshold: 5,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-katla",
    category_id: "cat-freshwater",
    name: "Katla",
    slug: "katla",
    description: "Rich, oily freshwater fish — Bengali classic.",
    cut_notes: "Whole or pieces",
    unit: "kg",
    price_paise: 32000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.5,
    categories: DEMO_CATEGORIES[0],
    inventory: {
      product_id: "prod-katla",
      qty_on_hand: 30,
      reserved_qty: 0,
      low_stock_threshold: 4,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-pomfret",
    category_id: "cat-seawater",
    name: "White Pomfret",
    slug: "white-pomfret",
    description: "Delicate seawater pomfret — perfect for fry.",
    cut_notes: "Whole, gutted",
    unit: "kg",
    price_paise: 78000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.5,
    categories: DEMO_CATEGORIES[1],
    inventory: {
      product_id: "prod-pomfret",
      qty_on_hand: 12,
      reserved_qty: 1,
      low_stock_threshold: 3,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-mackerel",
    category_id: "cat-seawater",
    name: "Bangda (Mackerel)",
    slug: "bangda",
    description: "Oily coastal mackerel — great grilled or fried.",
    cut_notes: "Whole",
    unit: "kg",
    price_paise: 24000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.5,
    categories: DEMO_CATEGORIES[1],
    inventory: {
      product_id: "prod-mackerel",
      qty_on_hand: 28,
      reserved_qty: 0,
      low_stock_threshold: 5,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-prawns",
    category_id: "cat-shellfish",
    name: "Tiger Prawns",
    slug: "tiger-prawns",
    description: "Firm tiger prawns — medium size.",
    cut_notes: "Deveined on request",
    unit: "kg",
    price_paise: 65000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.25,
    categories: DEMO_CATEGORIES[2],
    inventory: {
      product_id: "prod-prawns",
      qty_on_hand: 18,
      reserved_qty: 0,
      low_stock_threshold: 3,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: "prod-hilsa",
    category_id: "cat-freshwater",
    name: "Hilsa (Ilish)",
    slug: "hilsa",
    description: "Seasonal prized hilsa — limited stock.",
    cut_notes: "Whole or pieces",
    unit: "kg",
    price_paise: 120000,
    gst_rate: 5,
    image_url: null,
    is_active: true,
    min_order_qty: 0.5,
    categories: DEMO_CATEGORIES[0],
    inventory: {
      product_id: "prod-hilsa",
      qty_on_hand: 6,
      reserved_qty: 0,
      low_stock_threshold: 2,
      updated_at: new Date().toISOString(),
    },
  },
];

export function isSupabaseConfigured() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anon) return false;
  if (url.includes("your-project")) return false;
  if (anon.includes("your-anon-key") || anon.length < 40) return false;
  return true;
}
